### ISSUE TITLE
Can not create Sketch file from Example's generate_sketch

### ISSUE THREAD

**Issue by SirArkimedes** [Yelp/salsa#2]
Following the directions here: [README Link](https://github.com/Yelp/salsa/blob/master/README.md#example-project)

I get this output upon running `generate_sketch`:
```
Fatal error: Could not find font: SFProText-Semibold: file /Users/~/Developer/salsa/SalsaCompiler/SalsaCompiler/SketchJson/Text+SketchJson.swift, line 76
./generate_sketch: line 19: 10945 Illegal instruction: 4  ../SalsaCompiler/build/Release/salsa -f /tmp/SalsaExample/generated.salsa -e ExampleSketch
Failed to build sketch file
```

I'm wondering if this is because of version mismatch? I had to update `generate_sketch`'s first `xcodebuild` command. I changed the simulator to iOS 11.3, since Xcode 9.3 does not support the 10.3.1 simulator.

Versions:
`xcodebuild`: 9.3
Cocoapods: 1.5.0

**Comment by mrabiciu** [comment]
The example app is using iOS system fonts which are not available by default with macOS. Unfortunately trying to instantiate an  NSFont with a font that is not available on your machine just causes a crash instead of returning an optional 😞 

I'll update the example app to use a font that ships with macOS. But in the meantime if you can download the missing fonts from here: https://developer.apple.com/fonts/ and re-run the script.

**Comment by mrabiciu** [comment]
Updated to use the 11.3 simulator and changed font to HelveticaNeue which should come packaged with macOS.

**Comment by SirArkimedes** [comment]
That worked! Thanks!
